name: Simple Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ '*' ]
#    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  make_check:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        config:
          - ''
          - 'OPENSSL_TAG=master'
          - 'WOLFSSL_TAG=master'
          - 'OPENSSL_TAG=master WOLFSSL_TAG=master'
        force_fail:
          - ''
          - 'WOLFPROV_FORCE_FAIL=1'

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Run normal build and tests
        if: ${{ !matrix.force_fail }}
        run: |
          # Build with matrix config
          ${{ matrix.config }} ./scripts/build-wolfprovider.sh; BUILD_RESULT=$?

          # Run normal tests
          ./scripts/cmd_test/do-cmd-tests.sh; TEST_RESULT=$?

          # Check normal test results
          if [ $BUILD_RESULT -ne 0 ] || [ $TEST_RESULT -ne 0 ]; then
            echo "Normal build/test failed unexpectedly"
            exit 1
          fi

      - name: Run force-fail build and tests
        if: ${{ matrix.force_fail }}
        run: |
          # Build with matrix config and force fail
          ${{ matrix.config }} WOLFPROV_FORCE_FAIL=1 ./scripts/build-wolfprovider.sh; BUILD_RESULT=$?

          # Run tests with force fail
          WOLFPROV_FORCE_FAIL=1 ./scripts/cmd_test/do-cmd-tests.sh; TEST_RESULT=$?

          # Check force-fail results - we expect failures
          if [ $BUILD_RESULT -eq 0 ] || [ $TEST_RESULT -eq 0 ]; then
            echo "Force-fail build/test unexpectedly succeeded"
            exit 1
          else
            echo "Force-fail build/test failed as expected"
            exit 0
          fi

      - name: Print test logs
        if: always()
        run: |
          [ -f test-suite.log ] && cat test-suite.log
